//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperAutoBuddy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperAutoBuddy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;champion&quot;,&quot;format&quot;:&quot;standAloneComplex&quot;,&quot;version&quot;:&quot;6.9.1&quot;,&quot;data&quot;:{&quot;Aatrox&quot;:{&quot;version&quot;:&quot;6.9.1&quot;,&quot;id&quot;:&quot;Aatrox&quot;,&quot;key&quot;:&quot;266&quot;,&quot;name&quot;:&quot;Aatrox&quot;,&quot;title&quot;:&quot;the Darkin Blade&quot;,&quot;blurb&quot;:&quot;Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox&apos;s ...&quot;,&quot;info&quot;:{&quot;attack&quot;:8,&quot;defense&quot;:4,&quot;magic&quot;:3,&quot;difficulty&quot;:4},&quot;image&quot;:{&quot;full&quot;:&quot;Aatrox.pn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string champion {
            get {
                return ResourceManager.GetString("champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;item&quot;,&quot;version&quot;:&quot;6.9.1&quot;,&quot;basic&quot;:{&quot;name&quot;:&quot;&quot;,&quot;rune&quot;:{&quot;isrune&quot;:false,&quot;tier&quot;:1,&quot;type&quot;:&quot;red&quot;},&quot;gold&quot;:{&quot;base&quot;:0,&quot;total&quot;:0,&quot;sell&quot;:0,&quot;purchasable&quot;:false},&quot;group&quot;:&quot;&quot;,&quot;description&quot;:&quot;&quot;,&quot;colloq&quot;:&quot;;&quot;,&quot;plaintext&quot;:&quot;&quot;,&quot;consumed&quot;:false,&quot;stacks&quot;:1,&quot;depth&quot;:1,&quot;consumeOnFull&quot;:false,&quot;from&quot;:[],&quot;into&quot;:[],&quot;specialRecipe&quot;:0,&quot;inStore&quot;:true,&quot;hideFromAll&quot;:false,&quot;requiredChampion&quot;:&quot;&quot;,&quot;stats&quot;:{&quot;FlatHPPoolMod&quot;:0,&quot;rFlatHPModPerLevel&quot;:0,&quot;FlatMPPoolMod&quot;:0,&quot;rFlatMPModPerLevel&quot;:0,&quot;PercentHPPoolMod&quot;:0,&quot;PercentMPPoolMod&quot;:0,&quot;FlatHPRegenM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MageBuilds {
            get {
                return ResourceManager.GetString("MageBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vampiric;boots of speed;bt;berserker;runaan;rfc;ie;ga;.
        /// </summary>
        internal static string MarksmanBuilds {
            get {
                return ResourceManager.GetString("MarksmanBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NavGraphSummonersRift {
            get {
                object obj = ResourceManager.GetObject("NavGraphSummonersRift", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
